apiVersion: database.db-operator.io/v1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  # TODO(user): Add fields here
